version: "3.8"

services:
  monolith:
    build:
      context: ../monolith
      dockerfile: Dockerfile
    container_name: hotelio-monolith
    ports:
      - "8084:8080"
    networks:
      - hotelio-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://monolith-db:5432/hotelio
      SPRING_DATASOURCE_USERNAME: hotelio
      SPRING_DATASOURCE_PASSWORD: hotelio
      BOOKING_SERVICE_EXTERNAL_HOST: booking-service
      BOOKING_SERVICE_EXTERNAL_PORT: 50051

  monolith-db:
    image: postgres:15
    container_name: hotelio-db
    environment:
      POSTGRES_USER: hotelio
      POSTGRES_PASSWORD: hotelio
      POSTGRES_DB: hotelio
    ports:
      - "5432:5432"
    volumes:
      - monolith-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - hotelio-net
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - hotelio-net

  booking-service:
    build:
      context: ../booking-service
      dockerfile: Dockerfile
    container_name: booking-service
    ports:
      - "50051:50051"
    networks:
      - hotelio-net
    environment:
      DB_URL: postgresql://hotelio:hotelio@booking-service-db:5432/hotelio
      MONOLITH_API_URL: http://monolith:8080/api
      KAFKA_URL: kafka:9092
      KAFKA_BOOKING_TOPIC: bookings
    depends_on:
      booking-service-db:
        condition: service_healthy
        restart: true

  booking-service-db:
    image: postgres:15
    container_name: booking-service-db
    environment:
      POSTGRES_USER: hotelio
      POSTGRES_PASSWORD: hotelio
      POSTGRES_DB: hotelio
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hotelio -d hotelio" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5433:5432"
    volumes:
      - booking-service-data:/var/lib/postgresql/data
      - ../booking-service-db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - hotelio-net

  booking-history-service:
    build:
      context: ../booking-history-service
      dockerfile: Dockerfile
    container_name: booking-history-service
    networks:
      - hotelio-net
    environment:
      DB_URL: postgresql://hotelio:hotelio@booking-history-service-db:5432/hotelio
      KAFKA_URL: kafka:9092
      KAFKA_BOOKING_TOPIC: bookings
    depends_on:
      booking-history-service-db:
        condition: service_healthy
        restart: true

  booking-history-service-db:
    image: postgres:15
    container_name: booking-history-service-db
    environment:
      POSTGRES_USER: hotelio
      POSTGRES_PASSWORD: hotelio
      POSTGRES_DB: hotelio
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hotelio -d hotelio" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5434:5432"
    volumes:
      - booking-history-service-data:/var/lib/postgresql/data
      - ../booking-history-service-db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - hotelio-net

volumes:
  monolith-db-data:
  booking-service-data:
  booking-history-service-data:

networks:
  hotelio-net:
    external: true
